### ISSUE TITLE
How can I fix this?

### ISSUE THREAD

**Issue by smallerYeet** [civilwargeeky/Civils_Progs#11]
My Mining Turtle is stuck in [this](https://imgur.com/a/ktaNaOv) screen

**Comment by civilwargeeky** [comment]
Hello! This happens when the current fuel is greater than the fuel that was saved in the run restore file. To continue the program starting, you just need to press any key (to be fair, I probably should have mentioned that in the prompt).

The reason the turtle waits for user input in this case instead of continuing is because the turtle having more fuel than it was stopped with indicated that a server was rolled back, but the turtle's files weren't, so the turtle would think it was in the wrong place and mine where it wasn't supposed to.

The relevant code is on line 538 if you want to remove it.

Thanks for using the program!
