### ISSUE TITLE
I'm having errors resuming a turtle after a server reboot.

### ISSUE THREAD

**Issue by TheDoctorsLife** [civilwargeeky/Civils_Progs#8]
![2016-03-28_12 42 56](https://cloud.githubusercontent.com/assets/7450443/14083268/c35e70c2-f4e2-11e5-905c-5ea591d8234d.png)
This happens both with and without a GPS network.

**Comment by civilwargeeky** [comment]
Around line 810 (in the most recent version), go to the save progress function and look for a line like this:
`local function saveProgress(extras) --Session persistence
exclusions = { modem = true, shell = true, _ENV = true}
if doBackup then
local toWrite = ""
for a,b in pairs(getfenv(1)) do
  if not exclusions[a] then
      --print(a ,"   ", b, "   ", type(b)) --Debug`

Delete the "--" before the print statement, run the program, it will error, then add the table that it last prints to the exclusions table.

If you could also let me know what table offends so that I may add it to the exclusions for everyone, that would be great. Thanks for letting me know!

**Comment by TheDoctorsLife** [comment]
Sure thing

**Comment by TheDoctorsLife** [comment]
I'm stuck on this bit, can't get you what you need.
![2016-03-29_11 30 21](https://cloud.githubusercontent.com/assets/7450443/14113634/cecb79a4-f5a1-11e5-81a1-9d3aa8e68c20.png)

**Comment by civilwargeeky** [comment]
Ah, that just means that you have moved the turtle since the quarry was last run. I should probably put a timer in there, but all you have to do is hit a letter key and it will continue the rest of the quarry.
